---
title: "auxfunctions"
author: "GeoffRussell"
date: "2023-11-29"
output: html_document
---

## Note that this file and SouthAustralianElectricity/auxfunction.Rmd are different ... I should merge them and remove one.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(wbstats)
comma<-function(x) prettyNum(signif(x,digits=4),big.mark=",")
```

```{r}
dfjune<-read_csv("SouthAustralianElectricity/openNEMMerge-June-2024.csv") %>% select(date,`Solar (Utility) - MW`,`Solar (Rooftop) - MW`) %>% mutate(us=`Solar (Utility) - MW`,rs=`Solar (Rooftop) - MW`,ratiorsus=ifelse(us==0,0,ifelse(rs/us>10,10,rs/us))) %>% select(date,rs,us,ratiorsus) 
dfjune %>% filter(ratiorsus!=0)%>% ggplot(aes(x=date,y=ratiorsus))+ geom_line()
rat<-dfjune$ratiorsus
cat("\n")
summary(rat)

p<-dfjune %>% ggplot(aes(x=date,y=ratiorsus))+geom_line()+
  geom_text(aes(x=dfjune$date[500],y=9.5,hjust=0,label=paste0("Mean: ",comma(mean(rat)))),color="red")+
  labs(title="Ratio of Rooftop solar to Utility scale solar (South Australia)",x="")
p
png("Ratio-rooftop-solar-to-utility-(SA).png",width=5000,height=800,units="px",res=200,type="cairo-png")
print(p)
dev.off()
```

```{r}
dfm<-read_csv("openNEMMerge-25-05-2024-9D.csv") %>% mutate(demand=select(.,`Battery (Charging) - MW`:`Solar (Rooftop) - MW`) %>% apply(1,sum)) 
```

```{r}
removeIncomplete<-function(df) {
  ix1=0
  ix2=0
  for(i in 1:nrow(df)) {
    d<-as.character(df$date[i])
    if (ix1==0 & str_length(d)==10) {
#      cat(paste0("gotit1\n"))
      ix1=i
      break
    }
  }
  s=seq(nrow(df),1,-1)
  for(i in s) {
    d<-as.character(df$date[i])
#    cat(paste0(i," d:",d," ",nrow(df)," ",str_length(d),"\n"))
    if (ix2==0 & str_length(d)==10) {
#      cat(paste0("gotit2\n"))
      ix2=i-1
      break
    }
  }
#  cat(paste0("\nix1:",ix1," ix2:",ix2,"\n"))
  dfout<-df[ix1:ix2,]
}
# build the demand and also a second demand without Battery discharging
dfm<-read_csv("openNem-SA-30-05-24-7D.csv") %>% 
  mutate(demand=select(.,`Battery (Charging) -  MW`:`Solar (Rooftop) -  MW`) %>% apply(1,sum))  %>%
  mutate(d2=select(.,`Battery (Charging) -  MW`:`Solar (Rooftop) -  MW`) %>% 
           select(-`Battery (Discharging) -  MW`,-`Battery (Charging) -  MW`) %>% apply(1,sum)) 
# remove incomplete days
dfm2<-removeIncomplete(dfm) %>% mutate(dd=substr(as.character(date),9,10)) 

dfmout<-dfm2 %>% group_by(dd) %>% 
  summarise(pvwa=sum(demand*`Price - AUD/MWh`)/sum(demand),
            pavc=mean(`Price - AUD/MWh`),
            pvwa2=sum(d2*`Price - AUD/MWh`)/sum(d2),
            pavc2=mean(`Price - AUD/MWh`))
```

```{r}
findBands<-function(df) {
  sunbreak=0.05*max(df$`Solar (Rooftop) - MW`)  # 5 percent of max is start of day
  dark<-(df$`Solar (Rooftop) - MW`<sunbreak)    # which periods are dark
  ldld<-which(dark[-1] != dark[-length(dark)])  # where are the changes of state
  darkdf<-tribble(~t1,~t2)
  st<-2                                         
  if (dark[1]) {                                # are we starting in the night or the day?
     tmp<-tibble(t1=df$Time[1],t2=df$Time[ldld[1]],r1=1,r2=ldld[1])
     darkdf<-bind_rows(darkdf,tmp)
     st<-3
  }
  for (i in seq(st,length(ldld),2)) {
    tmp<-tibble(t1=df$Time[ldld[i-1]],t2=df$Time[ldld[i]],r1=ldld[i-1],r2=ldld[i])
    darkdf<-bind_rows(darkdf,tmp)
  }
  darkdf
}

```

```{r}
d<-"SouthAustralianElectricity/"
# very annoying different columns in wind and solar sheets
lookups<-c(
  'Megawatts'='...1',
  '2000'='...6', '2001'='...7', '2002'='...8', '2003'='...9', '2004'='...10',
  '2005'='...11', '2006'='...12', '2007'='...13', '2008'='...14', '2009'='...15',
  '2010'='...16', '2011'='...17', '2012'='...18', '2013'='...19', '2014'='...20',
  '2015'='...21', '2016'='...22', '2017'='...23', '2018'='...24', '2019'='...25',
  '2020'='...26', '2021'='...27', '2022'='...28'
  )
lookupw<-c(
  'Megawatts'='...1',
  '2000'='...5', '2001'='...6', '2002'='...7', '2003'='...8', '2004'='...9',
  '2005'='...10', '2006'='...11', '2007'='...12', '2008'='...13', '2009'='...14',
  '2010'='...14', '2011'='...16', '2012'='...17', '2013'='...18', '2014'='...19',
  '2015'='...20', '2016'='...21', '2017'='...22', '2018'='...23', '2019'='...24',
  '2020'='...25', '2021'='...26', '2022'='...27'
  )

getEnergySheet<-function(s,t) {
  read_xlsx(paste0(d,"Statistical_Review_of_World_Energy_2023.xlsx"),sheet=s,skip=2) %>%
    mutate(Country=`Terawatt-hours`) %>% select(Country,`2005`:`2022...59`) %>% mutate("2022"=`2022...59`) %>%
    select(Country,`2022`) %>% mutate(Type=t,TWh=`2022`) %>% select(Country,TWh,Type)
}

getElectricitySheet<-function(s) {
  read_xlsx(paste0(d,"Statistical_Review_of_World_Energy_2023.xlsx"),sheet=s,skip=2) %>% mutate("2022"=`2022...39`) %>%
    mutate(Country=`Terawatt-hours`,TWh=`2022`) %>% select(Country,TWh)  
}
dfel<-getElectricitySheet("Electricity Generation")
getCapacitySheet<-function(s,l) {
  read_xlsx(paste0(d,"Statistical_Review_of_World_Energy_2023.xlsx"),sheet=s,skip=2) %>% rename(all_of(l)) %>%
    mutate(Country=`Megawatts`) %>% select(Country,`2005`:`2022`)
}
```

## Get World Bank Population Data

We read the World Bank data and then save it for future use. The names of countries as used by the World
Bank don't match those used in the Statistical Review of World Energy; which is really annoying.

```{r}
# pop_data <- wb_data("SP.POP.TOTL", start_date = 2005, end_date = 2022) 
# write_csv(pop_data,"population2022.csv")
```

```{r capacity}
dfs <- getCapacitySheet("Solar Capacity",lookups) 
dfw <- getCapacitySheet("Wind Capacity",lookupw) 
countries<-read_csv("countries.csv") %>% arrange(Country)
population<-read_csv("population2022.csv")
lut<-c("United States"="US",
       "Korea, Rep."="South Korea")
pop <- population %>% mutate(country=recode(country,!!!lut))
write_csv(pop,paste0(d,"populationRenamed2022.csv"))
pop2022<-pop %>% filter(date=="2022") %>% mutate(Population=`SP.POP.TOTL`,Country=country) %>% select(Country,Population)
dfs2022 <- dfs %>% select(Country,`2022`) %>% left_join(pop2022) %>% inner_join(countries) %>% filter(!is.na(Population)) %>% mutate(MW=`2022`,kwPerCap=(MW*1000)/Population) 
write_csv(dfs2022,paste0(d,"kwPerCap2022.csv"))
dfw2022 <- dfw %>% select(Country,`2022`) %>% left_join(pop2022) %>% inner_join(countries) %>% filter(!is.na(Population)) %>% mutate(MW=`2022`,kwPerCap=(MW*1000)/Population) 
write_csv(dfw2022,paste0(d,"kwPerCap2022Wind.csv"))
countries<-dfw2022 %>% arrange(desc(kwPerCap)) %>% slice_head(n=20) %>% select(Country)
```

```{r testing}
dfdata<-read_csv(paste0(d,"opennem-30-11-2023sa5.csv")) %>% 
  rename_with(~sub('date','Time',.x)) %>% 
  rename_with(~sub('  ',' ',.x))
dfout<-dfdata %>% mutate(demand=select(.,`Battery (Charging) - MW`:`Solar (Rooftop) - MW`) %>% apply(1,sum)) 
write_csv(dfout,"dfout.csv")
dfimp<-dfdata %>% mutate(Imports=select(.,`Imports - MW`),Battery=`Battery (Discharging) - MW`,
                         Price=`Price - AUD/MWh`,BP=Price*Battery,IP=Price*Imports) %>%
  select(Battery,Imports,Price,BP,IP) %>% 
  summarise(sumb=sum(Battery),sumi=sum(Imports),avb=sum(BP)/sum(Battery),avi=sum(IP)/sum(Imports)) 
```

```{r renewable2022}
l<-tribble(
  ~s,                       ~t,
  "Geo Biomass Other - TWh","Biomass",
  "Wind Generation - TWh",  "Wind",
  "Solar Generation - TWh", "Solar", 
  "Hydro Generation - TWh", "Hydro",
  "Nuclear Generation - TWh", "Nuclear"
  )
addCountryPop<-function(.data) {
    .data %>% 
    left_join(pop2022,by=join_by(Country)) %>% 
    inner_join(countries,by=join_by(Country)) %>% filter(!is.na(Population)) 
}
dfsa<-tribble(
  ~Country,~TWh,~Type,~Population,
  "South Australia",3.758,"Solar",1.8e6,
  "South Australia",6.383,"Wind",1.8e6
) %>% mutate(kWhPerCap=as.numeric(TWh*1e9)/Population)
summary(dfsa)
dfyear<-bind_rows(map2(l$s,l$t,getEnergySheet)) %>% mutate(TWh=as.numeric(TWh)) %>% addCountryPop() %>%
  filter(!grepl("\\^|-",TWh)) %>% arrange(Country) %>% mutate(kWhPerCap=as.numeric(TWh)*1e9/Population)
summary(dfel)
dfel<-dfel %>% addCountryPop() 
summary(dfyear); summary(dfsa)
dfyear<-bind_rows(dfyear,dfsa)

write_csv(dfyear,paste0(d,"wsbh.csv"))
write_csv(dfel,paste0(d,"el.csv"))

```

```{r batteryusage}
dfbatt<-read_csv(paste0(d,"batteryusage2023.csv"))
dfbattout<-dfbatt %>% mutate(MWh=MW5*5/60,MWhI=IM5*5/60) %>% arrange(desc(MWh))
dfbattout %>% ggplot() + 
  geom_col(aes(x=ymd(date),y=MWh)) + 
  geom_smooth(aes(x=ymd(date),y=MWh)) 

```
```{r yearbyday}
dfybd<-read_csv(paste0(d,"opennem-3-12-2023sayearbyday.csv")) %>%
  rename_with(~sub('date','Date',.x)) %>% rename_with(~sub('  ',' ',.x)) %>%
  mutate(Month=str_sub(Date,1,7))
dfybdsum<-dfybd %>% summarise(ex=sum(`Exports - GWh`),im=sum(`Imports - GWh`),bat=sum(`Battery (Discharging) - GWh`))
dfyvals<-dfybd %>% summarise(battValPerGWh=sum(`Battery (Discharging) Market Value - AUD`)/sum(`Imports - GWh`),impValPerGWh=sum(`Imports Market Value - AUD`)/sum(`Imports - GWh`))
```

```{r batteriesbystate}
statepops<-tribble(
  ~Region,~Population,~Increase,
"New South Wales",8294.0,156.3,
"Victoria",6766.6,161.7,
"Queensland",5418.5,124.2,
"South Australia",1844.6,29.2,
"Western Australia",2855.6,78.3,
"Tasmania",572.7,2.4,
"Northern Territory",251.7,2.1,
"Australian Capital Territory",464.6,8.9
) %>% mutate(Population=Population*1000,Increase=Increase*1000)
df0<-read_csv(paste0(d,"facilities-australia.csv")) 
dff<-read_csv(paste0(d,"facilities-australia.csv")) %>% filter(grepl("Discharging",Technology)) %>%
  group_by(Region) %>% summarise(Capacity=sum(`Generator Capacity (MW)`)) %>% inner_join(statepops) %>% mutate(CapPerCap=Capacity*1e6/Population) %>% select(-Increase)
write_csv(dff,paste0(d,"BatCapPerRegion.csv"))
```
