---
title: "frequency-nem"
author: "GeoffRussell"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## Data 

```{r data}
D="/home/geoff/ARTICLES/GRID/"
R="Mainland frequency data"
gety<-function(yy) {
  f<-paste0(D,R," ",yy,".xlsx")
  print(f)
  nm<-paste0(c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),"-",yy)
  print(c("Time",nm))
  read_excel(f,sheet="Frequency data",skip=1,col_names=c("Time",nm))
}
df2010<-gety("2010")
df2011<-gety("2011")
df2022<-gety("2022")
df2023<-gety("2023")
```

```{r}
analyse<-function(fr) {
  nhigh<-0
  nlow<-0
  for (v in fr) {
    if (!is.na(v)) {
      if (v<49.85) { nlow=nlow+1; }
      if (v>50.15) { nhigh=nhigh+1; }
    }
  }
  c(h=nhigh,l=nlow)
}
df<-tibble(Time=df2010$Time)
df<-bind_cols(df,
              df2010[,2:ncol(df2010)],
              df2011[,2:ncol(df2011)],
              df2022[,2:ncol(df2022)],
              df2023[,2:ncol(df2023)])
colnames(df)

```

```{r}
o1<-df %>% reframe(across("Jan-2010":"Dec-2023",~analyse(.x))) 
to1<-tibble(Month=row.names(t(o1)),L=t(o1)[,1],H=t(o1)[,2]) 
```
```{r}
to2<-to1 %>% separate(Month,into=c("Month","Year"),sep="-")
to2 %>% ggplot() + geom_linerange(aes(x=Month,ymin=L,ymax=H)) + facet_grid(.~Year)
```

```{r}
analyse<-function(fr) {
  nhigh<-0
  nlow<-0
  for (v in fr) {
    if (!is.na(v)) {
      if (v<49.85) { nlow=nlow+1; }
      if (v>50.15) { nhigh=nhigh+1; }
    }
  }
  c(nhigh,nlow)
}
colnames(df)
print("2010")
for (df in c(df2010k))
analyse(df2010$`Jan-2010`)
analyse(df2010$`Feb-2010`)
analyse(df2010$`Mar-2010`)
analyse(df2010$`Apr-2010`)
analyse(df2010$`May-2010`)
analyse(df2010$`Jun-2010`)
analyse(df2010$`Jul-2010`)
analyse(df2010$`Aug-2010`)
analyse(df2010$`Sep-2010`)
analyse(df2010$`Oct-2010`)
analyse(df2010$`Nov-2010`)
analyse(df2010$`Dec-2010`)
print("2011")

analyse(df2011$`Jan-2011`)
analyse(df2011$`Feb-2011`)
analyse(df2011$`Mar-2011`)
analyse(df2011$`Apr-2011`)
analyse(df2011$`May-2011`)
analyse(df2011$`Jun-2011`)
analyse(df2011$`Jul-2011`)
analyse(df2011$`Aug-2011`)
analyse(df2011$`Sep-2011`)
analyse(df2011$`Oct-2011`)
analyse(df2011$`Nov-2011`)
analyse(df2011$`Dec-2011`)
print("2022")

analyse(df2022$`Jan-2022`)
analyse(df2022$`Feb-2022`)
analyse(df2022$`Mar-2022`)
analyse(df2022$`Apr-2022`)
analyse(df2022$`May-2022`)
analyse(df2022$`Jun-2022`)
analyse(df2022$`Jul-2022`)
analyse(df2022$`Aug-2022`)
analyse(df2022$`Sep-2022`)
analyse(df2022$`Oct-2022`)
analyse(df2022$`Nov-2022`)
analyse(df2022$`Dec-2022`)
print("2023")

analyse(df2023$`Jan-2023`)
analyse(df2023$`Feb-2023`)
analyse(df2023$`Mar-2023`)
analyse(df2023$`Apr-2023`)
analyse(df2023$`May-2023`)
analyse(df2023$`Jun-2023`)
analyse(df2023$`Jul-2023`)
analyse(df2023$`Aug-2023`)
analyse(df2023$`Sep-2023`)
analyse(df2023$`Oct-2023`)
analyse(df2023$`Nov-2023`)
analyse(df2023$`Dec-2023`)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
